language: node_js
node_js:
      - "8.0"
branches:
      - feature/frontend_react
install:
      - npm install -g firebase-tools
      - npm install
script:
      - npm run build
after_success:
      - firebase deploy --token $FIREBASE_TOKEN
env:
  - CI=false
  - REACT_APP_HOMEPAGE=/
